.PHONY: clean All

All:
	@echo "----------Building project:[ Letter-Pyramid - Debug ]----------"
	@cd "Letter-Pyramid" && "$(MAKE)" -f  "Letter-Pyramid.mk"
clean:
	@echo "----------Cleaning project:[ Letter-Pyramid - Debug ]----------"
	@cd "Letter-Pyramid" && "$(MAKE)" -f  "Letter-Pyramid.mk" clean
